### ISSUE TITLE
bad rendering after page init

### ISSUE THREAD

**Issue by n0vakovic** [jasust/issues#2] opened 2019-01-11 14:15 UTC
URL: http://nymag.com/intelligencer/2018/12/how-much-of-the-internet-is-fake.html
After Page Init, web page looks weird

**Comment by jasust** [comment] 2019-01-14 15:21
Fixed in the next update for that and similar pages with the same cause. 
Still not looking great for some pages like: [https://stackoverflow.com/](https://stackoverflow.com/)

**Comment by jasust** [comment] 2019-01-24 12:13
The problem is no longer relevant for version 1.40 and above. If something similar occurs again, feel free to reopen the issue.

**Closed as completed by jasust** 2019-01-24 12:13 UTC
